### PR TITLE
Allow send email for epaad for organizations with Static Pooling

### PR DESCRIPTION
**Pull request by tockata**

### CODE REVIEW

**Comment by viandrea** [comment]
@tockata Hi Anatoli, shall I test it?

**Comment by tockata** [comment]
Hi @viandrea ,
Not yet - Tsvyatko didn't have a chance to make the changes yet. I will let you know when it is ready for testing.

**Comment by viandrea** [comment]
Got it, thank you! @tockata

**Comment by tockata** [comment]
@viandrea you can test now on staging.
If organization type is Camp or the "Is Static Pooling" switch is ON click on the "Send to Epaad" button will send an email with org. data. On staging the email will be sent to Tsvyatko's email - we will forward it to you.

**Pull request merged**
